
[[main]]
  name = "Inspire"
  url = "/inspire/"
  weight = 10


[[main]]
  name = "Friends of Hack"
  url = "/partners/"
  identifier = "partners"
  weight = 20

[[main]]
  name = "Library"
  weight = 30
  url = "/library/"

[[main]]
  name = "Event Agenda"
  weight = 40
  identifier = "agenda"
  url = "/agenda/"

[[main]]
  name = "Get Help"
  weight = 50
  identifier = "help"
  url = "/help/"

