[[main]]
  name = "Inspire"
  url = "/inspire/"
  weight = 10


[[main]]
  name = "Friends of Hack"
  url = "/partners/"
  weight = 20

[[main]]
  name = "Hack Arsenal"
  weight = 30
  url = "/library/"

[[main]]
  name = "Event Agenda"
  weight = 40
  url = "/agenda/"

[[main]]
  name = "Get Help"
  weight = 50
  url = "/help/"

[[inspire]]
  name="Industrial Metaverse"
  weight = 10
  url = "/inspire/industry"

[[inspire]]
  name="Metaverse in Retail"
  weight = 20
  url = "/inspire/retail"

[[inspire]]
  name="Metaverse & AI"
  weight = 30
  url = "/inspire/ai"